### ISSUE TITLE
How to get ra2yrcpp?

### ISSUE THREAD

**Issue by wszzyer** [shmocz/pyra2yr#1]
Could you explain how to install ra2yrcpp？The link in readme.md is unaccessiable for me. Thanks.

**Comment by wszzyer** [comment]
Thanks for your reply!
I am also a Red Alert player, and I really like your project. The architecture of this project is very beautiful, and I can also learn a lot of knowledge about coroutines and network communication from it.

**Comment by wszzyer** [comment]
Hello, I'm sorry to bother you again. May I ask how the progress of pyra2yr is going?

**Comment by shmocz** [comment]
Hello,

There was a small hiatus, but now we're almost ready to publish the project. I'm currently configuring the CI workflow to build, verify, and package a pre-built binary (the build process can be a little involved). Keep a watchful eye on https://github.com/CnCNet as it will be published there. 🙂️

**Comment by shmocz** [comment]
ra2yrcpp bundled with ra2yrproto and pyra2yr is now available at: https://github.com/shmocz/ra2yrcpp. It's still highly experimental and instructions are highly Linux-centric, but this will hopefully improve in the near future.

**Comment by wszzyer** [comment]
Thank you very much!!!!
